# Generated by Django 5.0.7 on 2024-08-15 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_videogame_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='moviereview',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='unique_movie_review'),
        ),
        migrations.AddConstraint(
            model_name='videogamereview',
            constraint=models.UniqueConstraint(fields=('user', 'video_game'), name='unique_videogame_review'),
        ),
    ]
