# Generated by Django 5.0.7 on 2024-09-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_moviereview_unique_movie_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='genre',
            field=models.CharField(choices=[('Action-Adventure', 'Action-Adventure'), ('RPG', 'Role-Playing'), ('FPS', 'FPS'), ('MMO', 'MMO'), ('Strategy', 'Strategy'), ('Sports', 'Sports'), ('Horror', 'Horror'), ('Fighting', 'Fighting'), ('Racing', 'Racing'), ('Platformer', 'Platformer'), ('Survival', 'Survival')], max_length=100, verbose_name='Genre'),
        ),
    ]
